name: ci

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  check_for_version_upgrade:
    name: Check for version upgrade
    runs-on: ubuntu-latest
    needs:
      - test
    outputs:
      from_version: ${{steps.step1.outputs.from_version}}
      to_version: ${{steps.step1.outputs.to_version}}
      is_upgraded_version: ${{steps.step1.outputs.is_upgraded_version}}
      is_pre_release: ${{steps.step1.outputs.is_pre_release}}
    steps:
      - uses: garronej/ts-ci@v2.1.0
        id: step1
        with: 
          action_name: is_package_json_version_upgraded
          branch: ${{github.head_ref || github.ref}}

  publish_deno:
    name: Publish to Deno
    runs-on: ubuntu-latest
    needs: 
      - check_for_version_upgrade
    if: |
      needs.check_for_version_upgrade.outputs.is_upgraded_version == 'true'
    steps:
      - uses: actions/checkout@v3
      - run: rm -r .github
      - name: Remove deno-dist branch if it exists
        run: git push origin :deno-dist || true
      - run: git checkout -b deno-dist
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build:deno
      - run: npx -y -p denoify remove_deno_dist_from_gitignore
        env:
          DRY_RUN: "0"
      - run: |
          git config --global user.name actions
          git config --global user.email actions@github.com
          git add -A
          git commit -am "Add deno distribution files"
          git push origin deno-dist
      - uses: softprops/action-gh-release@v1
        with:
          name: v${{needs.check_for_version_upgrade.outputs.to_version}}
          tag_name: v${{needs.check_for_version_upgrade.outputs.to_version}}
          target_commitish: deno-dist
          generate_release_notes: false
          draft: false
          prerelease: ${{needs.check_for_version_upgrade.outputs.is_pre_release == 'true'}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
      - name: Remove deno-dist branch
        run: git push origin :deno-dist

  publish_npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: 
      - check_for_version_upgrade
    if: |
      needs.check_for_version_upgrade.outputs.is_upgraded_version == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{secrets.NPM_TOKEN}}